
app:
  port: 8080
  supported_languages:
    - ml-IN
  local_dir: uploads
  database:
    host: localhost
    port: 5432
    user: postgres
    dbname: kirani
    type: postgres

aws_config:
  bucket: kirana-ai-audio
  region: ap-south-1

ai_config: 
  model: gpt-5-mini
  temperature: 
  reasoning_effort: minimal