
app:
  port: 8080
  supported_languages:
    - ml-IN

aws_config:
  use_s3: true
  bucket: kirana-ai-audio
  region: ap-south-1

ai_config: 
  model: gpt-5-mini
  temperature: 
  reasoning_effort: minimal
  